apiVersion: benchmark.example.com/v1alpha1
kind: Benchmark
metadata:
  name: example-benchmark
  namespace: ripsaw
spec:
  workload:
    name: smallfile
    args:
      clients: [1]
      operation: ["create", "read", "append"]
      threads: 1
      file-size: 4
      files: 100
      top: /mnt/
      fsync: y
